#!/bin/bash
# Regenerate the generalization report from whatever results exist, commit and push if
# anything changed, and print a health line. Driven on a 30-minute loop while the run is
# in flight.
#
# Paths are staged EXPLICITLY, never `git add -A`: the working tree also holds ~100 GB of
# downloaded activation blobs, fit caches and probe pickles, plus hf_token.txt and
# kaggle/kaggle.json. Those are gitignored as well, but the explicit list is the guard
# that does not depend on the ignore file staying correct.
set -u
cd /workspace/cc_based_auto_improvement || exit 1

.venv_claude/bin/python scripts/generalization_report.py >/dev/null 2>&1

git add reports/generalization_tests/ scripts/generalization_tests.py \
        scripts/generalization_report.py scripts/health_check.sh \
        scripts/publish_progress.sh .gitignore 2>/dev/null

if git diff --cached --quiet; then
  echo "publish: no changes ($(date -u '+%H:%M:%SZ'))"
else
  summary=$(for c in hu_ha instructions highstakes; do
    f=results_generalization/$c/eval_results.csv
    [ -f "$f" ] && echo -n "$c $(( $(wc -l < "$f") - 1 ))rows "
  done)
  git commit -q -m "chore(generalization): progress snapshot — ${summary:-no results yet}

Regenerated by scripts/publish_progress.sh.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>"
  if git push -q origin generalization_tests 2>&1; then
    echo "publish: pushed ($(git rev-parse --short HEAD)) ${summary}"
  else
    echo "publish: WARN push failed ($(git rev-parse --short HEAD))"
  fi
fi

bash scripts/health_check.sh 2>/dev/null | grep -E "^(gpu|host|run|hu_ha|instructions|highstakes|WARN)"
