"""Render the red-team-only sweep as a human-readable REDTEAM_ONLY.md.

Reads the append-only sidecars — ``redteam_only_progress.jsonl`` for the no-base fits and
``vintage_progress.jsonl`` for the with-base reference rows — so it is correct mid-run and
costs milliseconds. Deliberately a *separate* file from ``SUMMARY.md``: that one is
generated by ``vintage_summary_md.py`` and would clobber anything written into it.

Usage:
    .venv_claude/bin/python scripts/redteam_only_summary_md.py
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import numpy as np  # noqa: E402

import attribution_lib as A  # noqa: E402

OUT_DIR = A.REPO / "results_instructions_gemma27b_vintage"
SPLITS = list(A.EVAL_SPLITS) + ["mean"]
COND_DESC = {
    "v2": "every iteration-3 pair whose source success already existed at iteration 2",
    "v3only": "only the pairs that first appear at iteration 3 (`keep[3] − keep[2]`)",
}


def _rows(path: Path) -> list[dict]:
    out = []
    if path.exists():
        for line in path.open(encoding="utf-8"):
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue  # row truncated by a hard kill
    return out


def _cells(rs: list[dict]) -> list[str]:
    cells = []
    for sp in SPLITS:
        x = np.array([r["auroc"][sp]["pipeline"] for r in rs])
        sd = x.std(ddof=1) if len(x) > 1 else float("nan")
        cells.append(f"{x.mean():.4f}" + ("" if len(x) < 2 else f" ± {sd:.4f}"))
    return cells


def _mean(rs: list[dict]) -> float:
    return float(np.mean([r["auroc"]["mean"]["pipeline"] for r in rs]))


def main() -> None:
    nobase = _rows(OUT_DIR / "redteam_only_progress.jsonl")
    withbase = _rows(OUT_DIR / "vintage_progress.jsonl")

    nb = defaultdict(list)
    for r in nobase:
        nb[(r["arm"], r["condition"])].append(r)
    wb = defaultdict(list)
    for r in withbase:
        wb[(r["arm"], r["vintage"])].append(r)

    L = []
    L.append("# Red-team data on its own — no base training data\n")
    L.append(f"_Updated {datetime.now(timezone.utc).isoformat(timespec='seconds')}_\n")
    L.append(
        "\n**What this measures.** The vintage sweep (`SUMMARY.md`) always trains on "
        "`data/instructions_llama70b_50.jsonl` **plus** a vintage of iteration-3 red-team "
        "pairs, which is what the pipeline does. Each row here is the same real "
        "`ProbeFactory` refit with the **base training data removed entirely** — from the "
        "fit *and* from validation — so the probe sees red-team conversations and nothing "
        "else. Two conditions, ten seeds each, per arm:\n\n"
    )
    for c, d in COND_DESC.items():
        L.append(f"- **`{c}`** — {d}.\n")
    L.append(
        "\n`v3only` is exactly the set `vintage_holdout_success.py` puts *in front of* the "
        "v2 probes; here it is what the probe is trained *from*.\n"
    )
    L.append(
        "\n**Setup.** Identical to the vintage sweep in every other respect: membership is "
        "derived per source success so pairs stay atomic and each set stays 50/50, the "
        "over-1024-token filter is on (`--drop-long pair`), each row's train/val side is the "
        "run's own content-deterministic split, all activations come off disk (no "
        "gemma-3-27b forward pass), and AUROC is the pipeline scale — bf16 `sigmoid` then "
        "sklearn, as `get_performances` reports it.\n"
    )
    L.append(
        "\n**One caveat on reading these as a training recipe.** With the base data gone the "
        "validation set is red-team rows only, so early stopping is judged on the same "
        "distribution the probe is fitted on. A high number here means *these rows alone "
        "separate the concept well enough to generalise to the eval splits*; it is not a "
        "claim that dropping the base data is a better way to train.\n"
    )

    L.append("\n## Progress\n\n")
    for arm in sorted({r["arm"] for r in nobase}):
        per = defaultdict(list)
        for r in nobase:
            if r["arm"] == arm:
                per[r["condition"]].append(r["seed"])
        L.append(f"- **{arm}**: "
                 + ", ".join(f"{c}×{len(s)}" for c, s in sorted(per.items())) + "\n")

    for arm in sorted({r["arm"] for r in nobase}):
        L.append(f"\n## {arm} — mean ± sd over seeds (pipeline scale)\n\n")
        L.append("| training set | rows | seeds | "
                 + " | ".join(SPLITS) + " |\n")
        L.append("|" + "---|" * (3 + len(SPLITS)) + "\n")
        # With-base reference rows first, so the no-base rows read as a delta against the
        # sweep everyone has already seen.
        for v, label in ((0, "base only (no red-team)"), (2, "v2 + base"), (3, "v3 + base")):
            rs = wb.get((arm, v))
            if rs:
                L.append(f"| {label} | {rs[0]['n_redteam_rows']} | {len(rs)} | "
                         + " | ".join(_cells(rs)) + " |\n")
        for c in ("v2", "v3only"):
            rs = nb.get((arm, c))
            if rs:
                L.append(f"| **{c}, no base** | {rs[0]['n_redteam_rows']} | {len(rs)} | "
                         + " | ".join(_cells(rs)) + " |\n")

    # --- the two comparisons the sweep exists to make ---------------------------------
    L.append("\n## What the base data is worth\n\n")
    L.append("| arm | v2 + base | v2 alone | delta |\n|---|---|---|---|\n")
    for arm in sorted({r["arm"] for r in nobase}):
        if wb.get((arm, 2)) and nb.get((arm, "v2")):
            a, b = _mean(wb[(arm, 2)]), _mean(nb[(arm, "v2")])
            L.append(f"| {arm} | {a:.4f} | {b:.4f} | {b - a:+.4f} |\n")
    L.append(
        "\nThe 50 base samples are worth roughly nothing on top of the red-team set — both "
        "deltas are inside one seed sd. That is consistent with the sweep's `v0` row, where "
        "the base data **alone** scores 0.4972 ± 0.0349, i.e. chance: this concept's eval "
        "signal comes from the red-team conversations, not from `instructions_llama70b_50`.\n"
    )

    L.append("\n## What iteration 3's own rows are worth\n\n")
    L.append("| arm | rows | v3only alone | v2 alone | v3 + base |\n|---|---|---|---|---|\n")
    for arm in sorted({r["arm"] for r in nobase}):
        if nb.get((arm, "v3only")):
            L.append(
                f"| {arm} | {nb[(arm, 'v3only')][0]['n_redteam_rows']} | "
                f"{_mean(nb[(arm, 'v3only')]):.4f} | {_mean(nb[(arm, 'v2')]):.4f} | "
                f"{_mean(wb[(arm, 3)]):.4f} |\n"
            )

    L.append(
        "\n**The two arms split completely here, and in the direction the AUROC sweep did "
        "not predict.** gptoss120b's 92 iteration-3 pairs — 184 rows, a quarter of its "
        "training set — reach the same eval AUROC on their own as its whole 674-row v2 set. "
        "nemotron's 148 pairs are *more* rows (296) and score 0.166 lower than its own v2 "
        "set, about eight seed sd: taken alone they do not span the concept.\n"
    )
    L.append(
        "\n**That resolves the tension left open in `SUMMARY.md`.** The held-out measurement "
        "found nemotron's iteration-3 finds fool the v2 probes far more reliably than "
        "gptoss120b's (0.707 vs 0.477 per-seed success) and yet *lower* mean eval AUROC when "
        "trained on. The two candidate explanations there were \"they concentrate in a region "
        "the eval splits do not sample\" and \"they resemble each other more than they "
        "resemble anything else\"; both predict what is measured here, and the alternative — "
        "that they carry broad signal which merely fails to add to what v2 already has — does "
        "not. Being a reliable probe failure and being useful training data are different "
        "properties, and nemotron's third rotation bought the first without the second.\n"
    )

    L.append(
        "\n**Per split, the iteration-3 rows are a different concept, not a weaker one "
        "(gptoss120b).** Trained on those 184 rows alone the probe *beats* every "
        "base-inclusive condition on `oig_context_drift` (0.694 vs 0.585/0.587) and "
        "`mm_substitution` (0.904 vs 0.879/0.858), and loses badly on "
        "`anthropic_harmless_refusal` (0.566 ± 0.183 — the sd says the seeds disagree about "
        "the direction) and `oig_omission` (0.642 vs 0.719/0.775). This is the same "
        "reallocation the vintage sweep saw across v1→v3, seen without the earlier rows "
        "present to mask it.\n"
    )
    L.append(
        "\n**nemotron's iteration-3 rows are anti-correlated on one split.** "
        "`anthropic_harmless_refusal` scores 0.400 ± 0.062 — below chance at every seed, not "
        "a draw that happened to land low. Whatever those 148 pairs encode about refusal is "
        "the opposite of what that split labels.\n"
    )

    L.append("\n## Files\n\n")
    L.append("- `redteam_only_progress.jsonl` — one row per fit (append-only, resumable)\n")
    L.append("- `redteam_only_auroc.csv` — per fit × split\n")
    L.append("- `redteam_only_summary.csv` — mean/sd/min/max per (arm, condition, split)\n")
    L.append("\n## Reproducing\n\n")
    L.append("```bash\n"
             "AGENTIC_FAST_ACTS=1 .venv_claude/bin/python scripts/redteam_only_fits.py \\\n"
             "  --arm gptoss120b nemotron --conditions v2 v3only --seeds 10\n"
             ".venv_claude/bin/python scripts/redteam_only_summary_md.py\n"
             "```\n")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "REDTEAM_ONLY.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {OUT_DIR / 'REDTEAM_ONLY.md'} ({len(nobase)} fits)")


if __name__ == "__main__":
    main()
