#!/usr/bin/env python
"""Retrain experiment10_cloud's two BATCH-submission probes on red-team data
WITHOUT contrastive pairs, then eval.

Ablation of the contrastive-augmentation step for the two batch-submission
attacker arms (sibling of ``retrain_nocontrastive_llama70b50.py`` and
``retrain_nocontrastive_llama70b50_grok.py``, which covered the per-turn runs):

    hu_harm_llama1b_deepseekv4pro_batch  (attacker: deepseek-v4-pro, batch/blind)
    hu_harm_llama1b_gptoss120b_batch     (attacker: gpt-oss-120b,    batch/blind)

The original pipeline retrained each probe on ``base ∪ preprocessed(successes)``
where preprocessing = ``filter_dataset`` (drop confounders) +
``generate_contrastive_dataset`` (add opposite-class pairs, here generated by
gpt-5.1). This script reproduces the same three retrain iterations per run but
**keeps filter_dataset and drops the contrastive-pair generation** — i.e. plain
filtered red-team successes concatenated with the base data.

"Keep filter, drop contrastive" is implemented by monkeypatching
``agentic_redteam.preprocessing.generate_contrastive_dataset`` to an identity
that returns the filtered records unchanged (no LLM calls, so no
OPENROUTER_API_KEY is needed). ``retrain_probe`` is still driven with a
preprocessing config so ``filter_dataset`` runs exactly as it did originally.
``_build_redteam_dataset`` imports both names *inside the function body*, so the
patch takes effect regardless of import order.

DIFFERENCE FROM THE TWO EARLIER nocontrastive SCRIPTS: they left
``min_judge_confidence`` at its default of 0, but ``cli.iterative_retrain_main``
passes ``min_judge_confidence=config.judge.confidence_threshold`` — 7 in both
exp10 configs. Omitting it would silently widen the training set and confound
the contrastive ablation with a confidence-gate change, so it is passed here.

Everything the original batch runs produced is REUSED, nothing is overwritten:
  * The base-split activation cache and the per-conversation red-team activation
    cache both live in ``results_hu_harm_llama70b50_batch_ablation/base_activations``
    (shared across BOTH arms on purpose — the cache keys contain no per-arm
    knobs). Content-keyed, so the filtered originals hit whatever is already
    there and only genuinely new conversations cost a forward pass.
  * The eval activation cache (``eval_<split>-acts_full.pt`` per split) is reused;
    all four blobs already exist, so eval loads no LLM at all.
  * New probes, postprocessed snapshots, iteration subsets and comparison CSVs
    are written under fresh ``*_nocontrastive`` paths.

Run:
    .venv_claude/bin/python scripts/retrain_nocontrastive_hu_harm_llama1b_batch.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent

# --- monkeypatch: filter stays, contrastive becomes a no-op -----------------
import agentic_redteam.preprocessing as _pp


def _no_contrastive(records, **_kwargs):
    """Identity stand-in for generate_contrastive_dataset: keep the filtered
    originals, add no opposite-class pairs, make no LLM calls."""
    return list(records)


_pp.generate_contrastive_dataset = _no_contrastive

from agentic_redteam.config import PreprocessingConfig  # noqa: E402
from agentic_redteam.retrain import retrain_probe  # noqa: E402
from agentic_redteam.evaluation import evaluate_probe  # noqa: E402

# --- fixed inputs shared by both runs ---------------------------------------
BASE_TRAINING_DATA = REPO / "data" / "hu_harm_llama70b_50.jsonl"
EVAL_DATASET_DIR = REPO / "eval_sets/hu_ha"
# Shared, already-populated caches from the original batch runs. Both arms point
# at these in their configs' output: section.
BASE_ACT_CACHE = REPO / "results_hu_harm_llama70b50_batch_ablation" / "base_activations"
EVAL_ACT_CACHE = REPO / "results_hu_harm_llama70b50_batch_ablation" / "eval_activations"

# Training / eval knobs, matching the original batch configs + the CLI defaults
# the run script relied on, so the caches hit and the ablation is single-variable.
FILTER_PERCENTILE = 0.8          # preprocessing.filter_percentile
MIN_JUDGE_CONFIDENCE = 7         # judge.confidence_threshold
TEST_SIZE = 0.2                  # CLI --test-size default
SEED = 42                        # CLI --seed default
COMBINE_CONSECUTIVE = True       # eval.combine_consecutive_messages
CONVERT_TOOL_TO_ASSISTANT = True  # eval.convert_tool_to_assistant
EVAL_MAX_SAMPLES = None          # eval_max_samples: 0 in config → full split → acts_full.pt
ASSISTANT_CENTRIC = True         # preprocessing.assistant_centric (unused once patched)

# Preprocessing config: only filter_percentile is actually consumed (contrastive
# is patched out), so provider/model are placeholders that never reach an LLM.
PREPROC = PreprocessingConfig(
    model="__unused_no_contrastive__",
    provider="openrouter",
    filter_percentile=FILTER_PERCENTILE,
    assistant_centric=ASSISTANT_CENTRIC,
)

# One entry per attacker arm. ``probe_dir`` holds the original probes
# (probe_iter0 is the arch + metadata donor, unchanged); fp/fn are the original
# successes JSONLs written by the batch runs.
RUNS = [
    {
        "name": "hu_harm_llama1b_deepseekv4pro_batch",
        "probe_dir": REPO / "probes" / "hu_harm_llama1b_deepseekv4pro_batch",
        "fp": REPO
        / "results_hu_harm_llama70b50_deepseekv4pro_batch"
        / "deepseekv4pro_probing_fp.jsonl",
        "fn": REPO
        / "results_hu_harm_llama70b50_deepseekv4pro_batch"
        / "deepseekv4pro_probing_fn.jsonl",
    },
    {
        "name": "hu_harm_llama1b_gptoss120b_batch",
        "probe_dir": REPO / "probes" / "hu_harm_llama1b_gptoss120b_batch",
        "fp": REPO
        / "results_hu_harm_llama70b50_gptoss120b_batch"
        / "gptoss120b_probing_fp.jsonl",
        "fn": REPO
        / "results_hu_harm_llama70b50_gptoss120b_batch"
        / "gptoss120b_probing_fn.jsonl",
    },
]

# Reproduce the same 3 retrains the original loop did. Cutoff k → probe_iter{k+1},
# trained on successes with iteration <= k (iter1: iter-0 successes; iter2: 0+1;
# iter3: 0+1+2), matching how the JSONL grew across the original iterations.
CUTOFFS = [0, 1, 2]

NEW_RESULTS_DIR = REPO / "results_hu_harm_llama70b50_batch_nocontrastive"


def write_iteration_subset(src: Path, dst: Path, cutoff: int) -> int:
    """Copy rows of `src` with 0 <= iteration <= cutoff into `dst`. Returns row count."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with src.open() as fh, dst.open("w") as out:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            it = rec.get("iteration", -1)
            if isinstance(it, int) and 0 <= it <= cutoff:
                out.write(json.dumps(rec) + "\n")
                n += 1
    return n


def eval_to_rows(probe_path: Path, label: str) -> pd.DataFrame:
    df = evaluate_probe(
        probe_path,
        EVAL_DATASET_DIR,
        EVAL_ACT_CACHE,
        max_samples=EVAL_MAX_SAMPLES,
        seed=SEED,
        combine_consecutive_messages=COMBINE_CONSECUTIVE,
        convert_tool_to_assistant=CONVERT_TOOL_TO_ASSISTANT,
    )
    df = df.copy()
    df.insert(0, "round", label)
    return df


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--min-judge-confidence",
        type=int,
        default=MIN_JUDGE_CONFIDENCE,
        help="Keep red-team successes with judge_confidence >= this (default %(default)s, "
        "matching judge.confidence_threshold in both exp10 configs). Pass 10 to keep only "
        "maximum-confidence successes.",
    )
    p.add_argument(
        "--tag",
        default="",
        help="Suffix for the probe dirs and comparison CSVs, so a run at a different "
        "confidence gate does not overwrite the default one. E.g. --tag _conf10",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    min_conf = args.min_judge_confidence
    tag = args.tag
    print(f">>> min_judge_confidence={min_conf}  tag={tag!r}")

    NEW_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    for run in RUNS:
        name = run["name"]
        orig_probe_dir = run["probe_dir"]
        # Arch + metadata donor. retrain_probe trains a FRESH head via
        # ProbeFactory.build (no warm start), so this only supplies the
        # ProbeSpec and the pos/neg class labels.
        base_probe = orig_probe_dir / "probe_iter0.pkl"
        out_dir = REPO / "probes" / f"{name}_nocontrastive{tag}"
        subset_dir = out_dir / "subsets"
        out_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n{'=' * 70}\nRUN: {name}\n{'=' * 70}")
        for required in (base_probe, run["fp"], run["fn"]):
            if not Path(required).exists():
                raise FileNotFoundError(f"Missing input: {required}")

        eval_frames: list[pd.DataFrame] = []

        # iter0 = the untouched base probe (no red-team data, no contrastive).
        # Re-evaluating it also verifies this script reproduces the original
        # run's iter0 row exactly, which validates the eval cache + transforms.
        print("Evaluating iter0 (original base probe, unchanged) ...")
        eval_frames.append(eval_to_rows(base_probe, "iter0"))

        # Chain probes the way cli.iterative_retrain_main does
        # (base_probe_path=current_probe_path). Equivalent to always passing
        # probe_iter0 since only the arch/metadata are read, but faithful.
        current_probe = base_probe

        for k in CUTOFFS:
            it_label = f"iter{k + 1}"
            print(f"\n--- {name}: {it_label} (successes with iteration <= {k}) ---")

            fp_sub = subset_dir / f"{it_label}_fp.jsonl"
            fn_sub = subset_dir / f"{it_label}_fn.jsonl"
            n_fp = write_iteration_subset(run["fp"], fp_sub, k)
            n_fn = write_iteration_subset(run["fn"], fn_sub, k)
            print(f"Subset rows (all attempts, successes filtered downstream): "
                  f"fp={n_fp}, fn={n_fn}")

            new_probe = out_dir / f"probe_{it_label}.pkl"
            postproc = out_dir / f"redteam_postprocessed_{it_label}.jsonl"

            result = retrain_probe(
                jsonl_path=[fp_sub, fn_sub],
                base_probe_path=current_probe,
                base_training_data_path=BASE_TRAINING_DATA,
                new_probe_path=new_probe,
                preprocessing=PREPROC,          # filter_dataset runs; contrastive patched out
                contrastive_cache_path=None,    # never read the original run's cached pairs
                postprocessed_out_path=postproc,
                min_judge_confidence=min_conf,
                test_size=TEST_SIZE,
                seed=SEED,
                base_activation_cache_dir=BASE_ACT_CACHE,   # REUSE existing activations
                combine_consecutive_messages=COMBINE_CONSECUTIVE,
                convert_tool_to_assistant=CONVERT_TOOL_TO_ASSISTANT,
                verbose=True,
            )
            print(
                f"Saved probe -> {new_probe}  "
                f"(n_redteam={result.n_redteam_samples}, "
                f"n_total={result.n_training_samples_total})"
            )

            current_probe = new_probe

            print(f"Evaluating {it_label} ...")
            eval_frames.append(eval_to_rows(new_probe, it_label))

        comparison = pd.concat(eval_frames, ignore_index=True)
        out_csv = NEW_RESULTS_DIR / f"{name}_nocontrastive{tag}_comparison.csv"
        comparison.to_csv(out_csv, index=False)
        print(f"\nSaved comparison table -> {out_csv}")
        print(comparison.to_string(index=False))

    print(f"\nAll done. Comparison CSVs are under {NEW_RESULTS_DIR}")


if __name__ == "__main__":
    main()
